name: Build and Publish NuGet Package

on:
  push:
    branches:
       - '*'

jobs:
  build-and-publish-nuget-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.203

      - name: Checkout Geex.Common repository
        uses: actions/checkout@v2
        with:
          repository: geex-graphql/Geex.Common
          ref: master
          path: Geex.Common

      - name: Checkout MongoDB.Entities repository
        uses: actions/checkout@v2
        with:
          repository: geexboxs/MongoDB.Entities
          ref: master
          path: MongoDB.Entities

      - name: Restore dependencies
        run: dotnet restore

      - name: Build package
        run: dotnet pack --configuration Release

     
